export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# swiftenv
if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi

# tmux
export TERM=xterm-256color

# temp
function git_ignore_ios() {
  if cd ~/.gitignore/Github/gitignore; then git pull; cd $OLDPWD; else git clone git@github.com:github/gitignore.git ~/.gitignore/Github/gitignore; fi
  cp ~/.gitignore/Github/gitignore/Swift.gitignore .gitignore
}
